name: RBleug
description: Regilero's blog; Mostly tech things about web stuff.
author: regilero
author_email: regis.leroy@gmail.com
category_dir: /
tag_dir: tag
url: http://regilero.github.io
highlighter: pygments
markdown: rdiscount
# markdown: kramdown
# kramdown:
#  # use Github Flavored Markdown
#  input: GFM
#  # do not replace newlines by <br>s
#  hard_wrap: false

permalink: pretty
# this will prevent default github usage
safe: false
lsi: false
# highlighter: pygments
